spring.application.name=PRM
spring.datasource.url=jdbc:postgresql://localhost:5432/prm_db
spring.datasource.username=prm_user
spring.datasource.password=prm_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
jwt.secret=prm-super-secret-key-must-be-at-least-32-chars-long
jwt.expiry.hours=8
logging.level.com.tunitx.PRM=DEBUG
server.port=8080
scheduler.interval.ms=14400000